apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy  # name of deployment
  namespace: default
spec:
  replicas: 1  # number of replicas
  selector:
    matchLabels:
      app: app  # selector label 
  template:
    metadata:
      labels:
        app: app  # same selector label as deployment
    spec:
      containers:
      - name: students-database-dotnet-docker-app 
        image: students-database-dotnet-docker-app:latest
        imagePullPolicy: IfNotPresent  # Corrected line
        ports:
        - containerPort: 5000

---  # separates deployment and service
apiVersion: v1
kind: Service
metadata:
  name: app-service  # name of service
spec:
  type: NodePort  # service has to be accessible externally
  selector:
    app: app  # same selector label as deployment
  ports:
  - nodePort: 30001 
    port: 5000 
    targetPort: 5000 
